[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = [
  "npm install",
  "cd packages/shared && npm run build",
  "cd packages/backend && npm run db:generate",
  "cd packages/backend && npm run build"
]

[start]
cmd = "cd packages/backend && npm start"
